solution
mate-academy/py-token-authentication pull request #173
Opened 2023-04-10 14:06 UTC by ProdyRodion

2023-04-10 14:55 UTC, viktoria-rybenchuk approved these changes
GJ!

2023-04-14 16:30 UTC, YuriiKindrat requested changes

2023-04-14 16:30 UTC, YuriiKindrat commented on user/views.py
> +    permission_classes = (AllowAny, )
why do u need this ?

2023-04-17 10:27 UTC, wQuelS approved these changes
GJ

2026-03-11 20:27 UTC, closed without merging