solution
mate-academy/py-token-authentication pull request #6
Opened 2022-07-16 13:28 UTC by rotsen18

2022-07-18 11:40 UTC, Y-Havryliv requested changes

2022-07-18 11:40 UTC, Y-Havryliv commented on cinema/views.py
> +# class GenreViewSet(
remove comments

2022-07-18 14:49 UTC, hectorovych requested changes

2022-07-20 11:41 UTC, Magus6784 approved these changes

2022-07-20 14:46 UTC, MasterpieceElbow approved these changes

2023-05-21 07:50 UTC, closed without merging