'Solution'
mate-academy/py-token-authentication pull request #636
Opened 2024-10-04 06:37 UTC by Poznanskyi

2024-10-05 13:32 UTC, olena4reunited approved these changes

2024-10-07 10:24 UTC, MNDonut requested changes

2024-10-07 10:24 UTC, MNDonut commented on user/views.py
> +from rest_framework.authentication import TokenAuthentication
remove unused import

2024-10-09 10:24 UTC, MNDonut requested changes

2024-10-09 10:24 UTC, MNDonut commented on cinema/permissions.py
> +        return bool(
do you need bool here taking into account that all operators return boolean?

2024-10-11 10:17 UTC, MNDonut approved these changes

2025-09-18 13:14 UTC, closed without merging